### ISSUE TITLE
[bug] KeyError: '__deepcopy__'

### ISSUE THREAD

**Issue by k-bx** [hmarr/mongoengine#119]
<pre>
>>> import datetime
... from mongoengine import \
...     Document, ReferenceField, StringField, DateTimeField, ListField, \
...     Q
>>> class User(Document):
...     jid = StringField(max_length=200, required=True, unique=True)
...     nick = StringField(max_length=200, required=True, unique=True)
...     friends = ListField(ReferenceField('self'))
... 
...     def friends_ids(self):
...         return (x.id for x in self.friends)
...     
...     def num_overall_messages(self):
...         return len(Message.objects(user=self))
...     
...     def num_today_messages(self):
...         from openju.bl.message import num_today_messages
...         return num_today_messages(lambda q: q & Q(user=self))
... 
...     def last_friends_messages(self):
...         from openju.bl.message import get_last_messages
...         import ipdb; ipdb.set_trace()
...         return get_last_messages(q=lambda q: q & Q(user__in = self.friends))
... 
... class Message(Document):
...     user = ReferenceField(User, required=True)
...     body = StringField(required=True)
...     dt = DateTimeField(default=datetime.datetime.utcnow, required=True)
...     tags = ListField(StringField(max_length=50))
...     reply_to = ReferenceField('self')
...     
...     meta = {
...         'ordering': ['-dt']
...     }
...     
...     def get_replies(self):
...         from openju.bl.message import get_replies
...         return get_replies(self.id)
...     
...     def post_reply(self, user, reply_body):
...         from openju.bl.message import post_reply
...         return post_reply(self, user, reply_body)
... 
...     def is_reply(self):
...         return bool(self.reply_to)
>>> from mongoengine import connect
>>> connect('openju')
0: Database(Connection('localhost', 27017), u'openju')
>>> Message.objects(Q(reply_to__exists=False))
1: [<Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, '...(remaining elements truncated)...']
>>> Message.objects(Q(user__in = self.friends))
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    Message.objects(Q(user__in = self.friends))
NameError: name 'self' is not defined
>>> obj = User.objects.first()
>>> obj.friends
2: [<User: User object>]
>>> Message.objects(Q(user__in = obj.friends))
3: [<Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, <Message: Message object>, '...(remaining elements truncated)...']
>>> Message.objects(Q(reply_to__exists=False) & Q(user__in = obj.friends))
Traceback (most recent call last):
  File "/usr/lib/python2.6/pprint.py", line 60, in pformat
    return PrettyPrinter(indent=indent, width=width, depth=depth).pformat(object)
  File "/usr/lib/python2.6/pprint.py", line 119, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/usr/lib/python2.6/pprint.py", line 137, in _format
    rep = self._repr(object, context, level - 1)
  File "/usr/lib/python2.6/pprint.py", line 230, in _repr
    self._depth, level)
  File "/usr/lib/python2.6/pprint.py", line 242, in format
    return _safe_repr(object, context, maxlevels, level)
  File "/usr/lib/python2.6/pprint.py", line 327, in _safe_repr
    rep = repr(object)
  File "/usr/local/lib/python2.6/dist-packages/mongoengine/queryset.py", line 1131, in __repr__
    data = list(self[self._skip:limit])
  File "/usr/local/lib/python2.6/dist-packages/mongoengine/queryset.py", line 776, in __getitem__
    self._cursor_obj = self._cursor[key]
  File "/usr/local/lib/python2.6/dist-packages/mongoengine/queryset.py", line 427, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "/usr/local/lib/python2.6/dist-packages/mongoengine/queryset.py", line 405, in _collection
    if '_types' in self._query:
  File "/usr/local/lib/python2.6/dist-packages/mongoengine/queryset.py", line 300, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "/usr/local/lib/python2.6/dist-packages/mongoengine/queryset.py", line 198, in to_query
    query = self.accept(SimplificationVisitor())
  File "/usr/local/lib/python2.6/dist-packages/mongoengine/queryset.py", line 248, in accept
    return visitor.visit_combination(self)
  File "/usr/local/lib/python2.6/dist-packages/mongoengine/queryset.py", line 67, in visit_combination
    return Q(**self._query_conjunction(queries))
  File "/usr/local/lib/python2.6/dist-packages/mongoengine/queryset.py", line 85, in _query_conjunction
    combined_query.update(copy.deepcopy(query))
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 228, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.6/copy.py", line 189, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.6/copy.py", line 338, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 228, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.6/copy.py", line 171, in deepcopy
    copier = getattr(x, "__deepcopy__", None)
  File "/usr/local/lib/python2.6/dist-packages/bson/dbref.py", line 81, in __getattr__
    return self.__kwargs[key]
KeyError: '__deepcopy__'
</pre>

**Comment by k-bx** [comment]
Oh, it just can't do copy.deepcopy(Q(user__in = user.friends))

**Comment by k-bx** [comment]
I think it revers to https://groups.google.com/d/topic/mongokit/3WZTbYt9XYc/discussion

**Comment by k-bx** [comment]
ok, got it.
It's a DBRef bug.
in dbref:dbref.py classDBRef method **getattr** should be:
<code>
    def **getattr**(self, key):
        if key.startswith('__'):
            raise AttributeError
        return self.__kwargs[key]
</code>

While right now it's:
<code>
    def **getattr**(self, key):
        return self.__kwargs[key]
</code>

**Comment by k-bx** [comment]
https://github.com/martinkou/bson/issues/issue/6

**Comment by rozza** [comment]
HI,  I think this is now working in dev but it seems to be the related libraries - have you upgraded?

There are test cases in dev that do Q() & Q() that pass eg: `test_and_combination` and `test_q_clone`
