### ISSUE TITLE
OperationError using get_or_create: "Could not save document (can't map file memory - mongo requires 64 bit build for larger datasets)"

### ISSUE THREAD

**Issue by bsterne** [hmarr/mongoengine#142]
I have hit this issue a few times now.  I am not sure what preceding operations are required to get into this state, but at some point one of my collections stops being able to save new documents:

```
>>> i = Item.objects.get(id = "4d12beb689b0e671f1000352")
>>> iti, created = ItemToIndex.objects.get_or_create(item = i)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.6/dist-packages/mongoengine/queryset.py", line 586, in get_or_create
    doc.save()
  File "/usr/local/lib/python2.6/dist-packages/mongoengine/document.py", line 85, in save
    raise OperationError(message % unicode(err))
OperationError: Could not save document (can't map file memory - mongo requires 64 bit build for larger datasets)
```

I am happy to attach the relevant portions of the models in play here, but I already looked for circular references and other obvious places that would result in huge amounts of memory to be allocated.  I'm opening up an issue here to see if there are debugging steps you'd like me to take to investigate this.

**Comment by bsterne** [comment]
Bah, this is probably a case of me not rtfm'ing enough.  I came across [this blog post](http://blog.mongodb.org/post/137788967/32-bit-limitations) that I failed to see before.  It's not that my collections were too complex or had cycles, etc., I was just storing too much damn data.  I got thrown off at first because I was able to save new documents in another collection, but those turned out to be smaller records so I could add a few while I was under the size limit.  I'm going to close this now.
