### ISSUE TITLE
iterating over large queryset: too much data for sort() with no index

### ISSUE THREAD

**Issue by j0hnsmith** [hmarr/mongoengine#176]
I'm trying to iterate over a large queryset but am getting an error (stacktrace below). The [mongodb docs do mention this error](http://www.mongodb.org/display/DOCS/Indexes#Indexes-Using{{sort%28%29}}withoutanIndex), this happens when the data to be returned in bigger than 4mb.

I think you should be able to catch this and do something like queryset._collection.ensure_inded('_id')

```
for model in my_models:
```

  File "/home/awddev/python/lib/python2.7/site-packages/mongoengine/queryset.py", line 648, in next
    return self._document._from_son(self._cursor.next())
  File "/home/awddev/python/lib/python2.7/site-packages/pymongo/cursor.py", line 609, in next
    if len(self.__data) or self._refresh():
  File "/home/awddev/python/lib/python2.7/site-packages/pymongo/cursor.py", line 572, in _refresh
    self.__query_spec(), self.__fields))
  File "/home/awddev/python/lib/python2.7/site-packages/pymongo/cursor.py", line 541, in __send_message
    self.__tz_aware)
  File "/home/awddev/python/lib/python2.7/site-packages/pymongo/helpers.py", line 100, in _unpack_response
    error_object["$err"])
pymongo.errors.OperationFailure: database error: too much data for sort() with no index

**Comment by hmarr** [comment]
There should already be an implicit index on _id - I assume you're suggesting creating an index on the sort field after catching this exception. That should solve the issue, but I'm hesitant as most people wouldn't expect an index to be created in this situation - especially if it was a large index that used loads of memory and took ages to generate it could cause problems.

**Comment by j0hnsmith** [comment]
I'm not actually sorting anything, just filtering a queryset then iterating over it. I added an index to every field on my model in the hope that I wouldn't get this error but I still do. 

I don't understand what in the collection doesn't have an index? Can we discuss on IRC (I'm cerberos)

**Comment by hmarr** [comment]
Looks like you're not on IRC anymore - saw a bit of your discussion with Ross though and check out the code paste. Could you try the same query with PyMongo to see if the error still occurs. Also, an explain on the query may give some more information about what's actually going on.

**Comment by j0hnsmith** [comment]
I tried it with pymongo and it works as expected. So the problem is that the query mongoengine produces is different to the pymongo one that works.

FYI I've removed all the unnecessary indexes on my model (but this isn't relevant to the problem)

```
In [1]: from pymongo import Connection

In [2]: db = Connection().apache_logger

In [3]: db.ip.index_information()
Out[3]: 
{u'_id_': {u'key': [(u'_id', 1)], u'v': 0},
 u'_types_1': {u'background': False, u'key': [(u'_types', 1)], u'v': 0},
 u'_types_1_date_1': {u'background': False,
                      u'key': [(u'_types', 1), (u'date', 1)],
                      u'v': 0},
 u'_types_1_ip_1': {u'background': False,
                    u'key': [(u'_types', 1), (u'ip', 1)],
                    u'v': 0}}

In [4]: from mongoengine import *

In [5]: connect('apache_logger')
Out[5]: Database(Connection('localhost', 27017), u'apache_logger')

In [7]: import datetime

In [8]: d = datetime.datetime(2011, 5, 22)

In [10]: from models import IP

In [11]: ips = IP.objects(date=d)

In [12]: ips._collection_obj.index_information()
Out[12]: 
{u'_id_': {u'key': [(u'_id', 1)], u'v': 0},
 u'_types_1': {u'background': False, u'key': [(u'_types', 1)], u'v': 0},
 u'_types_1_date_1': {u'background': False,
                      u'key': [(u'_types', 1), (u'date', 1)],
                      u'v': 0},
 u'_types_1_ip_1': {u'background': False,
                    u'key': [(u'_types', 1), (u'ip', 1)],
                    u'v': 0}}

In [13]: for ip in ips:
   ....:     print ip.ip
   ....:     
   ....:     

---------------------------------------------------------------------------
OperationFailure                          Traceback (most recent call last)

/home/awddev/log_analysis/<ipython console> in <module>()

/home/awddev/python/lib/python2.7/site-packages/mongoengine/queryset.pyc in next(self)
    656             if self._limit == 0:
    657                 raise StopIteration
--> 658             return self._document._from_son(self._cursor.next())
    659         except StopIteration, e:
    660             self.rewind()

/home/awddev/python/lib/python2.7/site-packages/pymongo/cursor.pyc in next(self)
    607             raise StopIteration
    608         db = self.__collection.database
--> 609         if len(self.__data) or self._refresh():
    610             next = db._fix_outgoing(self.__data.pop(0), self.__collection)
    611         else:

/home/awddev/python/lib/python2.7/site-packages/pymongo/cursor.pyc in _refresh(self)
    570                               self.__collection.full_name,
    571                               self.__skip, self.__limit,
--> 572                               self.__query_spec(), self.__fields))
    573             if not self.__id:
    574                 self.__killed = True

/home/awddev/python/lib/python2.7/site-packages/pymongo/cursor.pyc in __send_message(self, message)
    539             response = helpers._unpack_response(response, self.__id,
    540                                                 self.__as_class,
--> 541                                                 self.__tz_aware)
    542         except AutoReconnect:
    543             db.connection.disconnect()

/home/awddev/python/lib/python2.7/site-packages/pymongo/helpers.pyc in _unpack_response(response, cursor_id, as_class, tz_aware)
     98             raise AutoReconnect("master has changed")
     99         raise OperationFailure("database error: %s" %
--> 100                                error_object["$err"])
    101 
    102     result = {}

OperationFailure: database error: too much data for sort() with no index

In [14]: 

In [15]: db.ip.find({'date': d}).explain()
Out[15]: 
{u'allPlans': [{u'cursor': u'BasicCursor', u'indexBounds': {}}],
 u'cursor': u'BasicCursor',
 u'indexBounds': {},
 u'indexOnly': False,
 u'isMultiKey': False,
 u'millis': 143,
 u'n': 88890,
 u'nChunkSkips': 0,
 u'nYields': 0,
 u'nscanned': 89455,
 u'nscannedObjects': 89455}

In [17]: ips = db.ip.find({'date': d})

In [18]: ips.count()
Out[18]: 88890

In [19]: for ip in ips:
    print ip['ip']
   ....:     
   ....:     
58.7.221.179
203.217.176.26
202.177.218.43
...
```

here's the key difference (compare the output to db.ip.find({'date': d}).explain() above)

```
In [21]: IP.objects(date=d).explain()
Out[21]: 
{u'allPlans': [{u'cursor': u'BtreeCursor _types_1_ip_1',
                u'indexBounds': {u'_types': [[u'IP', u'IP']],
                                 u'ip': [[{u'$minElement': 1},
                                          {u'$maxElement': 1}]]}},
               {u'cursor': u'BtreeCursor _types_1_date_1',
                u'indexBounds': {u'_types': [[u'IP', u'IP']],
                                 u'date': [[datetime.datetime(2011, 5, 22, 0, 0),
                                            datetime.datetime(2011, 5, 22, 0, 0)]]}},
               {u'cursor': u'BtreeCursor _types_1',
                u'indexBounds': {u'_types': [[u'IP', u'IP']]}},
               {u'cursor': u'BasicCursor', u'indexBounds': {}}],
 u'cursor': u'BtreeCursor _types_1_date_1',
 u'indexBounds': {u'_types': [[u'IP', u'IP']],
                  u'date': [[datetime.datetime(2011, 5, 22, 0, 0),
                             datetime.datetime(2011, 5, 22, 0, 0)]]},
 u'indexOnly': False,
 u'isMultiKey': False,
 u'millis': 4011,
 u'n': 88890,
 u'nChunkSkips': 0,
 u'nYields': 0,
 u'nscanned': 88890,
 u'nscannedObjects': 88890,
 u'scanAndOrder': True}
```

**Comment by hmarr** [comment]
In the document definition in the paste you posted, there's a default ordering defined as ['ip', 'date'], so this will be used in the MongoEngine query, but not in the PyMongo one. It looks like you didn't have a composite index on ip and date, so this could well be the problem.

Also, if you're not going to be subclassing IP, it may be worth adding `'allow_inheritance': False` to your `meta` dict, which will make the storage more efficient. To migrate the existing data, you'll need to run something like `db.ip.update({}, {$unset: {_types: 1, _cls: 1}}, false, true);` in your mongo shell, which will remove the extra information MongoEngine stores for handing inheritance.

**Comment by j0hnsmith** [comment]
I took the actions you suggested and now it works. Many thanks. I assume the composite index made the difference (I will test to make sure), here's the working output.

```
class IP(Document):
    ip = StringField(required=True)
    date = DateTimeField(required=True, unique_with='ip')
    total_requests = IntField(default=0)
    html_total = IntField(default=0)
    image_total = IntField(default=0)
    css_total = IntField(default=0)
    js_total = IntField(default=0)
    rates_total = IntField(default=0)
    flash_total = IntField(default=0)
    cgi_total = IntField(default=0)
    virtual_tour_total = IntField(default=0)
    pdf_total = IntField(default=0)
    favicon_total = IntField(default=0)
    unknown_total = IntField(default=0)
    meta = {
        'indexes': ['ip', 'date',],
        'allow_inheritance': False,
    }

In [12]: d = datetime.datetime(2011, 5, 24)

In [13]: IP.objects(date=d).count()
Out[13]: 103049

In [14]: IP.objects(date=d).explain()
Out[14]: 
{u'allPlans': [{u'cursor': u'BtreeCursor date_1',
                u'indexBounds': {u'date': [[datetime.datetime(2011, 5, 24, 0, 0),
                                            datetime.datetime(2011, 5, 24, 0, 0)]]}}],
 u'cursor': u'BtreeCursor date_1',
 u'indexBounds': {u'date': [[datetime.datetime(2011, 5, 24, 0, 0),
                             datetime.datetime(2011, 5, 24, 0, 0)]]},
 u'indexOnly': False,
 u'isMultiKey': False,
 u'millis': 379,
 u'n': 103049,
 u'nChunkSkips': 0,
 u'nYields': 0,
 u'nscanned': 103049,
 u'nscannedObjects': 103049,
 u'oldPlan': {u'cursor': u'BtreeCursor date_1',
              u'indexBounds': {u'date': [[datetime.datetime(2011, 5, 24, 0, 0),
                                          datetime.datetime(2011, 5, 24, 0, 0)]]}}}

In [15]: ips = IP.objects(date=d)

In [17]: ips._collection_obj.index_information()
Out[17]: 
{u'_id_': {u'key': [(u'_id', 1)], u'v': 0},
 u'date_1': {u'background': False, u'key': [(u'date', 1)], u'v': 0},
 u'date_1_ip_1': {u'background': False,
                  u'dropDups': False,
                  u'key': [(u'date', 1), (u'ip', 1)],
                  u'unique': True,
                  u'v': 0},
 u'ip_1': {u'background': False, u'key': [(u'ip', 1)], u'v': 0}}

In [18]: for ip in ips:
   ....:     print ip.ip
   ....:     
   ....:     
116.240.186.43
94.96.95.112
49.179.44.74
```

**Comment by rozza** [comment]
Good news!

Closing the issue
