### ISSUE TITLE
filtering with Q object fails in django 1.3

### ISSUE THREAD

**Issue by tkloc** [hmarr/mongoengine#185]
i have a simple queryset with Q object:

```
    post_list = Post.objects.filter(Q(thread_id=thread.id) | Q(id=thread.id))
```

it works fine with django 1.2.4 and lower, but after upgrade to 1.3 throws error:

```
Traceback:
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/core/handlers/base.py" in get_response
  111.                         response = callback(request, *callback_args, **callback_kwargs)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)
File "/secure/tomek/projects/parrot/../parrot/board/decorators.py" in _check_group
  34.             return view_func(request, group=group, *args, **kwargs)
File "/secure/tomek/projects/parrot/../parrot/board/decorators.py" in _check_thread
  60.         return view_func(request, thread=thread, *args, **kwargs)
File "/secure/tomek/projects/parrot/../parrot/board/views.py" in show_thread
  273.     return direct_to_template(request, template, locals())
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/views/generic/simple.py" in direct_to_template
  28.     return HttpResponse(t.render(c), mimetype=mimetype)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in render
  123.             return self._render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in _render
  117.         return self.nodelist.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in render
  744.                 bits.append(self.render_node(node, context))
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/debug.py" in render_node
  73.             result = node.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/loader_tags.py" in render
  127.         return compiled_parent._render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in _render
  117.         return self.nodelist.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in render
  744.                 bits.append(self.render_node(node, context))
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/debug.py" in render_node
  73.             result = node.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/loader_tags.py" in render
  127.         return compiled_parent._render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in _render
  117.         return self.nodelist.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in render
  744.                 bits.append(self.render_node(node, context))
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/debug.py" in render_node
  73.             result = node.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/loader_tags.py" in render
  127.         return compiled_parent._render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in _render
  117.         return self.nodelist.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in render
  744.                 bits.append(self.render_node(node, context))
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/debug.py" in render_node
  73.             result = node.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/loader_tags.py" in render
  127.         return compiled_parent._render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in _render
  117.         return self.nodelist.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in render
  744.                 bits.append(self.render_node(node, context))
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/debug.py" in render_node
  73.             result = node.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/loader_tags.py" in render
  64.             result = block.nodelist.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in render
  744.                 bits.append(self.render_node(node, context))
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/debug.py" in render_node
  73.             result = node.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/loader_tags.py" in render
  64.             result = block.nodelist.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/base.py" in render
  744.                 bits.append(self.render_node(node, context))
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/debug.py" in render_node
  73.             result = node.render(context)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/Django-1.3-py2.6.egg/django/template/defaulttags.py" in render
  191.         len_values = len(values)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/mongoengine-0.4-py2.6.egg/mongoengine/queryset.py" in __len__
  668.         return self.count()
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/mongoengine-0.4-py2.6.egg/mongoengine/queryset.py" in count
  665.         return self._cursor.count(with_limit_and_skip=True)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/mongoengine-0.4-py2.6.egg/mongoengine/queryset.py" in _cursor
  427.             self._cursor_obj = self._collection.find(self._query, 
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/mongoengine-0.4-py2.6.egg/mongoengine/queryset.py" in _query
  300.             self._mongo_query = self._query_obj.to_query(self._document)
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/mongoengine-0.4-py2.6.egg/mongoengine/queryset.py" in to_query
  198.         query = self.accept(SimplificationVisitor())
File "/home/tomek/environments/parrot/lib/python2.6/site-packages/mongoengine-0.4-py2.6.egg/mongoengine/queryset.py" in accept
  246.             self.children[i] = self.children[i].accept(visitor)

Exception Type: TemplateSyntaxError at /group/4cf24907fe50bc2cc000001f/thread/4de612386b66931a2100006b/
Exception Value: Caught AttributeError while rendering: 'dict' object has no attribute 'accept'
```

python2.6, mongoengine 0.4, django 1.3, mongod 1.6.0, pymongo 1.9

**Comment by rozza** [comment]
Can anyone else confirm?

**Comment by Ankhbayar** [comment]
Yes. Me too. 
Mongoengine is newest dev branch.
Django 1.3. 
PyMongo is 1.11.

Traceback (most recent call last):

```
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 123, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 117, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 744, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 757, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 127, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 117, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 744, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 757, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 64, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 744, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 757, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 313, in render
    return self.nodelist_false.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 744, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 757, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 311, in render
    return self.nodelist_true.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 744, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 757, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 191, in render
    len_values = len(values)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine-0.4-py2.7.egg/mongoengine/queryset.py", line 761, in __len__
    return self.count()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine-0.4-py2.7.egg/mongoengine/queryset.py", line 758, in count
    return self._cursor.count(with_limit_and_skip=True)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine-0.4-py2.7.egg/mongoengine/queryset.py", line 495, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "/usr/local/lib/python2.7/dist-packages/mongoengine-0.4-py2.7.egg/mongoengine/queryset.py", line 366, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine-0.4-py2.7.egg/mongoengine/queryset.py", line 206, in to_query
    query = self.accept(SimplificationVisitor())
  File "/usr/local/lib/python2.7/dist-packages/mongoengine-0.4-py2.7.egg/mongoengine/queryset.py", line 254, in accept
    self.children[i] = self.children[i].accept(visitor)
AttributeError: 'dict' object has no attribute 'accept'
```

**Comment by rozza** [comment]
Hi, currently I cant reproduce - I've added a test case which doesn't throw the error.

Can anyone produce / reproduce the error?

**Comment by rozza** [comment]
Hi guys - can you improve my test case to reproduce?

To run the tests simple do: python setup.py test

**Comment by Ankhbayar** [comment]
I Found this error. 
see this gist. https://gist.github.com/1028837

**Comment by rozza** [comment]
@Ankhbayar - thanks for the test case - double rendering triggers the bug.
