### ISSUE TITLE
KeyError when trying to create index on EmbeddedDocumentField

### ISSUE THREAD

**Issue by dhm116** [hmarr/mongoengine#257]
I haven't seen any examples on how to created indexes on embedded fields with mongoengine. Mongo supports this (using dot notation), however I've looked through all of the documentation and test cases to see if there was any working instances of this. Using a simple example like:

``` python
class Blah(Document):
    name = StringField()
    things = ListField(EmbeddedDocumentField('Thing'))

    meta = {
        'indexes': ['things.name']    
    }

class Thing(EmbeddedDocument):
    name = StringField()

    def __init__(self, name=None):
        super(Thing, self).__init__()

        self.name = name

if __name__ == '__main__':
    print 'Connecting to the test database'
    connect('embedded-index-test',host='localhost') # connect to test db

    Blah.drop_collection()
    blah = Blah()
    blah.name = 'Test'
    blah.things = [Thing('thing1'), Thing('thing2')]
    blah.save()
```

produces the following error:

```
Traceback (most recent call last):
  File "planning.py", line 35, in <module>
    class Blah(Document):
  File "build\bdist.win32\egg\mongoengine\base.py", line 277, in __new__
  File "build\bdist.win32\egg\mongoengine\queryset.py", line 337, in _build_index_spec
  File "build\bdist.win32\egg\mongoengine\queryset.py", line 457, in _lookup_field
  File "build\bdist.win32\egg\mongoengine\fields.py", line 354, in lookup_member
  File "build\bdist.win32\egg\mongoengine\fields.py", line 272, in lookup_member
  File "build\bdist.win32\egg\mongoengine\fields.py", line 250, in document_type
  File "build\bdist.win32\egg\mongoengine\base.py", line 12, in get_document
KeyError: 'Thing'
```

Any ideas or suggestions as to how to get this working?

**Comment by rozza** [comment]
Hi,

This works in the dev branch - I've added a couple of extra test cases showing how to set it and it working.

Ross
