### ISSUE TITLE
Errors in python setup.py test

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#260]
# 
## FAIL: test_dict_field (tests.dereference.FieldTest)

Traceback (most recent call last):
  File "/home/wilson/Lethus/social/vendor/mongoengine/tests/dereference.py", line 420, in test_dict_field
    self.assertEqual(q, 1)
AssertionError: -2 != 1
# 
## FAIL: test_dict_field_no_field_inheritance (tests.dereference.FieldTest)

Traceback (most recent call last):
  File "/home/wilson/Lethus/social/vendor/mongoengine/tests/dereference.py", line 511, in test_dict_field_no_field_inheritance
    self.assertEqual(q, 1)
AssertionError: -2 != 1
# 
## FAIL: test_generic_reference (tests.dereference.FieldTest)

Traceback (most recent call last):
  File "/home/wilson/Lethus/social/vendor/mongoengine/tests/dereference.py", line 174, in test_generic_reference
    self.assertEqual(q, 1)
AssertionError: -2 != 1
# 
## FAIL: test_generic_reference_map_field (tests.dereference.FieldTest)

Traceback (most recent call last):
  File "/home/wilson/Lethus/social/vendor/mongoengine/tests/dereference.py", line 599, in test_generic_reference_map_field
    self.assertEqual(q, 1)
AssertionError: -2 != 1
# 
## FAIL: test_list_field_complex (tests.dereference.FieldTest)

Traceback (most recent call last):
  File "/home/wilson/Lethus/social/vendor/mongoengine/tests/dereference.py", line 265, in test_list_field_complex
    self.assertEqual(q, 1)
AssertionError: -2 != 1
# 

FAIL: test_list_item_dereference (tests.dereference.FieldTest)
## Ensure that DBRef items in ListFields are dereferenced.

Traceback (most recent call last):
  File "/home/wilson/Lethus/social/vendor/mongoengine/tests/dereference.py", line 40, in test_list_item_dereference
    self.assertEqual(q, 1)
AssertionError: -2 != 1
# 
## FAIL: test_map_field_reference (tests.dereference.FieldTest)

Traceback (most recent call last):
  File "/home/wilson/Lethus/social/vendor/mongoengine/tests/dereference.py", line 341, in test_map_field_reference
    self.assertEqual(q, 1)
AssertionError: -2 != 1
# 

FAIL: test_recursive_reference (tests.dereference.FieldTest)
## Ensure that ReferenceFields can reference their own documents.

Traceback (most recent call last):
  File "/home/wilson/Lethus/social/vendor/mongoengine/tests/dereference.py", line 97, in test_recursive_reference
    self.assertEqual(q, 1)
AssertionError: -2 != 1
# 

FAIL: test_bulk_insert (tests.queryset.QuerySetTest)
## Ensure that query by array position works.

Traceback (most recent call last):
  File "/home/wilson/Lethus/social/vendor/mongoengine/tests/queryset.py", line 470, in test_bulk_insert
    self.assertEqual(q, 2) # 1 for the inital connection and 1 for the insert
AssertionError: -2 != 2

---

Ran 221 tests in 4.310s

FAILED (failures=9)

**Comment by rozza** [comment]
Wheres this? On the latest dev I'm getting:

```
----------------------------------------------------------------------
Ran 221 tests in 5.013s

OK
```

**Comment by rozza** [comment]
@wpjunior ping!

**Comment by wpjunior** [comment]
I just run on a clean installation

same error :-(

**Comment by rozza** [comment]
hmm - what versions of mongodb and pymongo?

**Comment by rozza** [comment]
I've just tried with a clean virtual env and with pymongo 1.11 all tests pass..

**Comment by rozza** [comment]
Commit bda716ef9d721248a9f3 fixes tests for pymongo 2.0.1

**Comment by wpjunior** [comment]
community/mongodb [installed: 1.8.2-4]
community/python2-pymongo 1.10.1-1 [installed]

**Comment by rozza** [comment]
I cant reproduce :(

**Comment by rozza** [comment]
can you try checking out an older known working commit and see if it still errors?
