### ISSUE TITLE
slice: IndexError: stop index must be greater than startindex for slice 

### ISSUE THREAD

**Issue by kittle** [hmarr/mongoengine#336]
```
>>> len(models.SpeechAct.objects)
259

>>> models.SpeechAct.objects[0]
<SpeechAct: # onedirectionatheat You will  ...>

>>> models.SpeechAct.objects[10:11]
[<SpeechAct: 2 . ...>]

>>> models.SpeechAct.objects[100:101]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mongoengine/queryset.py", line 1615, in __repr__
    data = list(self[self._skip:limit])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mongoengine/queryset.py", line 1028, in __getitem__
    raise err
IndexError: stop index must be greater than startindex for slice slice(100, 21, None)
```

**Comment by rozza** [comment]
Thanks for the code - now fixed in dev
