### ISSUE TITLE
indexes in Abstract document

### ISSUE THREAD

**Issue by koblas** [hmarr/mongoengine#380]
When the following base class is used on a subsequent document there is an error tha tthe user_guid is not a approprate field dictionary (in the indexes).  Everything works fine if I change it to to index_background (which isn't present in the subclass).  Makes me belive there is an bug somewhere (I couldn't find it).  

```
class UserModelMixin(Document):
    meta = {
            'abstract' : True,
            'index'  : ['user_guid'],
    }

    user_guid  = StringField(required=True)

    def __init__(self, user=None, *args, **kwargs):
        super(UserModelMixin, self).__init__(*args, **kwargs)

        if user:
            self.user_guid = user.guid
            self._user_cache = user

    @property
    def user(self):
        if not hasattr(self, '_user_cache'):
            self._user_cache = User.objects.get(guid=self.user_guid)
        return self._user_cache
```

**Comment by rozza** [comment]
The current test case works for me in `dev` and `0.5.2`

```
    def test_index_inheritance(self):
        class UserModelMixin(Document):
            meta = {
                    'abstract' : True,
                    'index'  : ['user_guid'],
            }

            user_guid  = StringField(required=True)


        class Person(UserModelMixin):
            name = StringField()

        Person.drop_collection()

        test = Person(name="test", user_guid='123')
        test.save()

        self.assertEquals(1, Person.objects.count())
```

**Comment by koblas** [comment]
Two things:

Shouldn't that be `indexes` not `index` (which was a typo in my original - sorry).

Here's a simple unittest that fails:

```
import unittest
from mongoengine import connect, Document, StringField

connect('unittest')

class Test(unittest.TestCase):
    def test_index_inheritance(self):
        class UserModelMixin(Document):
            meta = {
                    'abstract' : True,
                    'indexes'  : ['user_guid'],
            }

            user_guid  = StringField(required=True)


        class Person(UserModelMixin):
            meta = {
                    'indexes'  : ['name'],
            }

            name = StringField()

        Person.drop_collection()

        test = Person(name="test", user_guid='123')
        test.save()

        self.assertEquals(1, Person.objects.count())

if __name__ == '__main__':
    unittest.main()
```

The error I get is:

```
======================================================================
ERROR: test_index_inheritance (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "xx.py", line 27, in test_index_inheritance
    test.save()
  File "/usr/lib64/python2.7/site-packages/mongoengine-0.5.2-py2.7.egg/mongoengine/document.py", line 154, in save
    collection = self.__class__.objects._collection
  File "/usr/lib64/python2.7/site-packages/mongoengine-0.5.2-py2.7.egg/mongoengine/queryset.py", line 511, in _collection
    opts['unique'] = spec.get('unique', False)
AttributeError: 'str' object has no attribute 'get'

----------------------------------------------------------------------
```

**Comment by rozza** [comment]
Sorry, I adapted the original example!  OK this makes more sense now!

**Comment by rozza** [comment]
@koblas  - thanks for the ticket all fixed in dev
