### ISSUE TITLE
Test fail: QuerySetTest.test_update_pull

### ISSUE THREAD

**Issue by husio** [hmarr/mongoengine#48]
```
# python setup.py test -q || git log --oneline | head -n 1
0.3
running test
running egg_info
writing requirements to mongoengine.egg-info/requires.txt
writing mongoengine.egg-info/PKG-INFO
writing top-level names to mongoengine.egg-info/top_level.txt
writing dependency_links to mongoengine.egg-info/dependency_links.txt
reading manifest file 'mongoengine.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
writing manifest file 'mongoengine.egg-info/SOURCES.txt'
running build_ext
........................................................E..........................
======================================================================
ERROR: Ensure that the 'pull' update operation works correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/sda5/Projekty/virtualenvs/mongoengine/mongoengine/tests/queryset.py", line 646, in test_update_pull
    BlogPost.objects(slug="test").update(pull__comments__content="test2")
  File "/mnt/sda5/Projekty/virtualenvs/mongoengine/mongoengine/mongoengine/queryset.py", line 718, in update
    raise OperationError(u'Update failed (%s)' % unicode(err))
OperationError: Update failed (Modifier spec implies existence of an encapsulating object with a name that already represents a non-object, or is referenced in another $set clause)

----------------------------------------------------------------------
Ran 83 tests in 0.462s

FAILED (errors=1)
[1]    9833 exit 1     python setup.py test -q
eecc618 fixes issue #41 since unicode kwargs is an feature of python 2.6.5 and above.
```

**Comment by husio** [comment]
After git pull, all tests are passing.
