### ISSUE TITLE
mongoengine 0.6.9 is not compatible with pymongo 2.2

### ISSUE THREAD

**Issue by nautilebleu** [hmarr/mongoengine#509]
For now, when downloading mongoengine from PyPI, we also get download pymongo 2.2, as the package doesn't set exact pymongo version.

**Comment by rozza** [comment]
mongoengine 0.6.9 does work with pymongo 2.2 - all tests pass against it.

http://travis-ci.org/#!/MongoEngine/mongoengine

Any specific issues you are seeing?

**Comment by nautilebleu** [comment]
I've downloaded from PyPi and got a 0.6.9 release of mongoengine, which
comes with pymongo2.2.

When starting django, I've an ImportError for pymongo.code.

This module is not in pymongo2.2. When backporting pymongo to 2.1.1 with
pip install --upgrade pymongo==2.1.1, everything works again.

Thus my thinking that mongoengine should require explicity pymongo 2.1.1.

2012/5/23 Ross Lawley <
reply@reply.github.com

**Comment by rozza** [comment]
Ah ok - can you provide the trace back?  code should come from the bson library

**Comment by nautilebleu** [comment]
Here the traceback:

```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    import settings
  File "/Users/goulwen/Dev/GreenBureau/front/gb_site/settings.py", line 309, in <module>
    from mongoengine import connect
  File "/Users/goulwen/Dev/GreenBureau/front/venv/src/mongoengine/mongoengine/__init__.py", line 1, in <module>
    import document
  File "/Users/goulwen/Dev/GreenBureau/front/venv/src/mongoengine/mongoengine/document.py", line 3, in <module>
    from base import (DocumentMetaclass, TopLevelDocumentMetaclass, BaseDocument,
  File "/Users/goulwen/Dev/GreenBureau/front/venv/src/mongoengine/mongoengine/base.py", line 1, in <module>
    from queryset import QuerySet, QuerySetManager
  File "/Users/goulwen/Dev/GreenBureau/front/venv/src/mongoengine/mongoengine/queryset.py", line 5, in <module>
    import pymongo.code
ImportError: No module named code
```

**Comment by rozza** [comment]
Ok, you have an old version of MongoEngine at /Users/goulwen/Dev/GreenBureau/front/venv/src/mongoengine/

That code was updated back in feb:  https://github.com/MongoEngine/mongoengine/commit/a59b518cf2ca53da5699ce34a95e15cc07561a6d

**Comment by nautilebleu** [comment]
Humm, I download it from PyPI with pip. I will check if the bug occurs when downloading it directly from github.

**Comment by rozza** [comment]
Do you have multiple versions installed?

**Comment by nautilebleu** [comment]
Nope, I've only one version in the venv. I start by upgrade it and since it
breaks, I end up removing mongoengine and pymongo and then reinstall from
scratch. When downloading again, I got the same error, until I force
pymongo to be in 2.1.1.

**Comment by rozza** [comment]
ok path issues are the only thing I can think of - its tested locally and on CI against pymongo 2.2.

Can you confirm the version your application is seeing?  Or try recreating your virtual environment - it is compatible :)

```
from mongoengine import get_version
print get_version()
```

or output:

```
cat /Users/goulwen/Dev/GreenBureau/front/venv/src/mongoengine/mongoengine/__init__.py
```

**Comment by nautilebleu** [comment]
Ok, I've checked both mongoengine and pymongo in the shell.

```
In [1]: from mongoengine import get_version

In [2]: print get_version()
0.6.9

In [3]: import pymongo

In [4]: pymongo.version
Out[4]: '2.2'
```

Then the traceback is different:

```
Traceback (most recent call last):
  File "/Users/goulwen/Dev/GreenBureau/back/venv/lib/python2.7/site-packages/celery/worker/job.py", line 106, in execute_safe
    return self.execute(*args, **kwargs)
  File "/Users/goulwen/Dev/GreenBureau/back/venv/lib/python2.7/site-packages/celery/worker/job.py", line 124, in execute
    return super(WorkerTaskTrace, self).execute()
  File "/Users/goulwen/Dev/GreenBureau/back/venv/lib/python2.7/site-packages/celery/execute/trace.py", line 90, in execute
    retval = self._trace()
  File "/Users/goulwen/Dev/GreenBureau/back/venv/lib/python2.7/site-packages/celery/execute/trace.py", line 104, in _trace
    r = handler(trace.retval, trace.exc_type, trace.tb, trace.strtb)
  File "/Users/goulwen/Dev/GreenBureau/back/venv/lib/python2.7/site-packages/celery/worker/job.py", line 139, in handle_success
    self.task.backend.mark_as_done(self.task_id, retval)
  File "/Users/goulwen/Dev/GreenBureau/back/venv/lib/python2.7/site-packages/celery/backends/base.py", line 88, in mark_as_done
    return self.store_result(task_id, result, status=states.SUCCESS)
  File "/Users/goulwen/Dev/GreenBureau/back/venv/lib/python2.7/site-packages/celery/backends/base.py", line 225, in store_result
    return self._store_result(task_id, result, status, traceback, **kwargs)
  File "/Users/goulwen/Dev/GreenBureau/back/venv/lib/python2.7/site-packages/celery/backends/mongodb.py", line 100, in _store_result
    from pymongo.binary import Binary
ImportError: No module named binary
```

**Comment by rozza** [comment]
Have you got two versions of mongoengine one for `back` venv and one for `front` venv?   Mongoengine 0.6.9 does not do this import:  `import pymongo.code`

Hmm Celery is another issue it has been updated, but hasn't been released to pip yet.  You could install from git, or manually add pymongo==2.1 to your requirements.txt file and all should work and then upgrade in the future.

**Comment by nautilebleu** [comment]
Yep, we have to venv, one fro `front` and `back`. They should have the same mongoengine but when checking this, I just switch one of the venv. Probably the first error (`import pymongo.code`) was due to a vent that was not completely cleaned (I found that if you have added a package with git, then switching to pipy, the previous package is not completely removed). 

Ok for the workaround.

**Comment by rozza** [comment]
Ah cool, glad we got there in the end.  I'm not sure when the next release of Celery will be - should be soon as they are on rc3.

**Comment by nautilebleu** [comment]
ok thanks.

**Comment by agrimaseth** [comment]
i have the following versions
mongoengine = 0.5.2
pymongo 2.7.2
and i am getting the following traceback files 

File "settings.py", line 157, in <module>
    from mongoengine import connect
  File "/usr/lib/python2.7/dist-packages/mongoengine/**init**.py", line 1, in <module>
    import document
  File "/usr/lib/python2.7/dist-packages/mongoengine/document.py", line 2, in <module>
    from base import (DocumentMetaclass, TopLevelDocumentMetaclass, BaseDocument,
  File "/usr/lib/python2.7/dist-packages/mongoengine/base.py", line 1, in <module>
    from queryset import QuerySet, QuerySetManager
  File "/usr/lib/python2.7/dist-packages/mongoengine/queryset.py", line 5, in <module>
    import pymongo.code
ImportError: No module named code

Kindly help
