### ISSUE TITLE
AttributeError: 'module' object has no attribute 'code'

### ISSUE THREAD

**Issue by ash4u** [hmarr/mongoengine#513]
My Code is : Message.objects.filter( Q(author_id=user.id) | Q(for_user_id=user.id) | Q( shared_with_id=user.id)).order_by( "-timestamp")[:10]

MongoDB = 1.8.2
Pymonogo :1.11

Traceback (most recent call last):

 File "/mnt/install/wwm/thirdparty/django/core/handlers/base.py", line 100, in get_response
   response = callback(request, _callback_args, *_callback_kwargs)

 File "/mnt/install/wwm/thirdparty/django/contrib/auth/decorators.py", line 25, in _wrapped_view
   return view_func(request, _args, *_kwargs)

 File "/mnt/install/wwm/main/views.py", line 1232, in user_messages
   mesg_list =  list(Message.objects( Q(author_id=user.id) | Q(for_user_id=user.id) | Q( shared_with_id=user.id)).order_by( "-timestamp")[:10])

 File "/mnt/install/wwm/thirdparty/mongoengine/queryset.py", line 223, in **call**
   self._where_clause = q_obj.as_js(self._document)

 File "/mnt/install/wwm/thirdparty/mongoengine/queryset.py", line 89, in as_js
   return pymongo.code.Code(' '.join(js), js_scope)

AttributeError: 'module' object has no attribute 'code'

The same line of code is working fine with 
pymongo : 2.0.1
mongodb : 2.1.0 

Where exactly is the error ?

**Comment by rozza** [comment]
Hi,

Pymongo 1.11 is no longer supported.  I would advise to updating pymongo if possible.  If not possible, you need to look at the imports as Code and others have been moved to the bson module.

Ross

**Comment by ash4u** [comment]
Thanks for quick response.
