### ISSUE TITLE
TypeError in `_delta` when documents reference each other

### ISSUE THREAD

**Issue by PaulUithol** [hmarr/mongoengine#518]
Hi,

In a (not too small) application, we have some documents that keep references (one-to-many) to each other. However, this seems to trip up MongoEngine. See the reduced testcase below:

``` python
import unittest

from mongoengine import *
import mongoengine


class Person( Document ):
    name = StringField()
    owns = ListField( ReferenceField( 'Organization' ) )

class Organization( Document ):
    name = StringField()
    owner = ReferenceField( 'Person' )


class DocumentTestCase( unittest.TestCase ):

    def setUp( self ):
        mongoengine.register_connection( mongoengine.DEFAULT_CONNECTION_NAME, 'mongoengine_test' )

    def tearDown( self ):
        pass

    def test_user( self ):
        person = Person( name="owner" )
        person.save()
        organization = Organization( name="company" )
        organization.save()

        person.owns.append( organization )
        organization.owner = person

        person.save()
        organization.save()
```

The last `save` raises an exception in `BaseDocument._delta`:

``` python
  File "*/test_mongoengine.py", line 34, in test_user
    organization.save()
  File "*\Python\Python27\lib\site-packages\mongoengine\document.py", line 224, in save
    self.cascade_save(**kwargs)
  File "*\Python\Python27\lib\site-packages\mongoengine\document.py", line 253, in cascade_save
    ref.save(**kwargs)
  File "*\Python\Python27\lib\site-packages\mongoengine\document.py", line 197, in save
    updates, removals = self._delta()
  File "*\Python\Python27\lib\site-packages\mongoengine\base.py", line 1054, in _delta
    d = getattr(p, d)
TypeError: getattr(): attribute name must be string
```

At this point, `d = getattr(p, d)` translates to `d = getattr( 'owner', DbRef(organization) )`. I don't know exactly what's going on here, but this doesn't look right at all. The intention is probably to do something like `getattr( organization, 'owner' )`?

**Comment by rozza** [comment]
Thanks for the bug report - fixed and will be 0.6.11

**Comment by PaulUithol** [comment]
Thanks! How about the order of the parameters for the `getattr` call though? Shouldn't they be reversed?

**Comment by rozza** [comment]
Full fix now in- was the cascading save trying to resave.  Also the branch of code you pointed out wasnt being hit - so has been removed.

Thanks for the follow up

**Comment by PaulUithol** [comment]
Hmm, with the latest version, I get an `AttributeError` on `d = d.get(p)` with our full code, while the version with the DbRef code did run. Maybe that should stay?

Update:
Alright, so when you have more 'levels' of models (say, `Organization` has `employees = ListField( ReferenceField( 'Employee' ) )`,
`d` can still be a DbRef, in which case it is necessary to treat those differently in `_delta`.

**Comment by PaulUithol** [comment]
Updated testcase:

``` python
import unittest

from mongoengine import *
import mongoengine


class Person( Document ):
    name = StringField()
    owns = ListField( ReferenceField( 'Organization' ) )
    employer = ReferenceField( 'Organization' )

class Organization( Document ):
    name = StringField()
    owner = ReferenceField( 'Person' )
    employees = ListField( ReferenceField( 'Person' ) )


class DocumentTestCase( unittest.TestCase ):

    def setUp( self ):
        mongoengine.register_connection( mongoengine.DEFAULT_CONNECTION_NAME, 'mongoengine_test' )

    def tearDown( self ):
        pass

    def test_save( self ):
        person = Person( name="owner" )
        person.save()

        employee = Person( name="employee" )
        employee.save()

        organization = Organization( name="company" )
        organization.save()

        person.owns.append( organization )
        organization.owner = person

        organization.employees.append( employee )
        employee.employer = organization

        person.save()
        organization.save()
```

Stacktrace:

``` python
Traceback (most recent call last):
  File "*\Python27\lib\unittest\case.py", line 327, in run
    testMethod()
  File "*/basic/test_mongoengine.py", line 43, in test_save
    organization.save()
  File "*\Python27\lib\site-packages\mongoengine\document.py", line 230, in save
    self.cascade_save(**kwargs)
  File "*\Python27\lib\site-packages\mongoengine\document.py", line 259, in cascade_save
    ref.save(**kwargs)
  File "*\Python27\lib\site-packages\mongoengine\document.py", line 202, in save
    updates, removals = self._delta()
  File "*\Python27\lib\site-packages\mongoengine\base.py", line 1050, in _delta
    d = d.get(p)
  File "*\Python27\lib\site-packages\bson\dbref.py", line 88, in __getattr__
    raise AttributeError(key)
AttributeError: get
```

**Comment by rozza** [comment]
Curses, the test suite didnt cover it.

new release coming..

On Tue, Jun 19, 2012 at 3:04 PM, Paul Uithol <
reply@reply.github.com

**Comment by rozza** [comment]
Ok fixed - but you need to add a employee.save() as well - cascading saves dont save through listfields / dicts as it would kill perf

**Comment by PaulUithol** [comment]
Yeah, I left out everything that wasn't necessary to trigger the exception ;). Thanks for the quick fixes!
