### ISSUE TITLE
Inheritance & unique keys problems

### ISSUE THREAD

**Issue by agonzalezro** [hmarr/mongoengine#532]
Hi!

I was looking through the issues and I didn't see this. Actually, I really don't know if it's a bug or possible normal behaviour.

``` python

class A(db.Document):
    meta = {'allow_inheritance': True}

class B(A):
    unique_required = db.IntField(unique=True, required=True)

def test():
    the_b = B(unique_required=1)
    the_b.save()

    the_a = A()
    the_a.save()

    the_a2 = A()
    the_a2.save()
```

This will break with this error:

```
*** OperationError: Tried to save duplicate unique keys (E11000 duplicate key error index: eelogic.a.$unique_required_1  dup key: { : null })
```

If I have a clear db with A document completely empty and I don't create any object type B, it doesn't break.

``` python
def test():
    the_a = A()
    the_a.save()

    the_a2 = A()
    the_a2.save()
```

**Comment by rozza** [comment]
Yes, this wont work unless its a sparse index.  You may need to manually
add this index.

On Tue, Jul 3, 2012 at 10:39 AM, Alexandre González <
reply@reply.github.com

**Comment by agonzalezro** [comment]
Sorry, I don't understand exactly what do you want me to do.

Do you want something like this?:

``` python
class A(db.Document):
    id_a = db.IntField(primary_key=True)
    meta = {'allow_inheritance': True,
            'indexes': (id_a, )}


class B(A):
    id_b = db.IntField(primary_key=True)
    unique_required = db.IntField(unique=True, required=True)

    meta = {'indexes': (id_b, )}
```

It seems very strange behavior for me, but I'm not very related with this inheritances on mongoengine.

Thanks!

**Comment by rozza** [comment]
Hi,

Sorry,  You cant declare unique indexes on an inherited document, without
making the index sparse.  Currently,
to do that you need to manually declare the index:

eg:

```
meta = {
    'indexes': [
        { 'fields': ['unique_required'], 'unique': True,
          'sparse': True, 'types': False },
    ],
}
```

On Tue, Jul 3, 2012 at 10:56 PM, Alexandre González <
reply@reply.github.com

**Comment by agonzalezro** [comment]
Hi again rozza,

I tried your solution and this one:

``` python
meta = {
    'indexes': [
        {'fields': ['unique_required'], 'sparse': True, 'unique': True},
    ]
}
```

That I found here: https://github.com/hmarr/mongoengine/issues/280

But pitifully, it breaks with this traceback:

```
Traceback (most recent call last):
  ...
  File "/home/alex/XXX/YYY/ZZZ/models.py", line 41, in <module>
    class B(A):
  File "/home/alex/.virtualenvs/XXX/site-packages/mongoengine/base.py", line 709, in __new__
    for spec in indicies] + base_indexes
  File "/home/alex/.virtualenvs/XXX/site-packages/mongoengine/queryset.py", line 500, in _build_index_spec
    if key.startswith("-"):
AttributeError: 'dict' object has no attribute 'startswith'
```

I'm sorry asking this here, since it's not a bug perhaps I should close the issue and move the conversation to another place like the mailing lists, but I think that this last traceback is a real error to me, should I create a new issue with it? It seems to b e related with the `direction` pull-request that I sent to you some days ago: https://github.com/hmarr/mongoengine/pull/531

**Comment by agonzalezro** [comment]
Closing because of inactivity. However, thanks for your time @rozza
