### ISSUE TITLE
startwith/istartwith do not handle regex error

### ISSUE THREAD

**Issue by GermanoGuerrini** [hmarr/mongoengine#58]
/mongoengine/fields.py, line 60, "prepare_query_value" doesn't catch re.error

**Comment by flosch** [comment]
Can you give an example where this might be helpful and how/why should it be catched?

TIA,
flosch

**Comment by GermanoGuerrini** [comment]
Hey,
I've seen it by using mongoengine as a part of an autocomplete system (you can see it at http://multiplayer.it/ on the top-right search field, where it read "Cerca nel sito..."). We received a few traceback when someone was looking for strings that contains parenthesis or quotes. For example:

 File "/usr/lib/python2.5/site-packages/django/core/handlers/base.py", line 100, in get_response
   response = callback(request, _callback_args, *_callback_kwargs)

 File "/usr/lib/python2.5/site-packages/mongo_autocomplete/views.py", line 13, in autocomplete
   items = Item.objects(label__istartswith=query)[:MAX_RESULTS]

 File "build/bdist.linux-i686/egg/mongoengine/queryset.py", line 215, in **call**
   query = QuerySet._transform_query(_doc_cls=self._document, **query)

 File "build/bdist.linux-i686/egg/mongoengine/queryset.py", line 322, in _transform_query
   value = field.prepare_query_value(op, value)

 File "build/bdist.linux-i686/egg/mongoengine/fields.py", line 60, in prepare_query_value
   value = re.compile(regex % value, flags)

 File "/usr/lib/python2.5/re.py", line 188, in compile
   return _compile(pattern, flags)

 File "/usr/lib/python2.5/re.py", line 241, in _compile
   raise error, v # invalid expression

error: unexpected end of regular expression

<WSGIRequest
GET:<QueryDict: {u'term': [u"Divinity 2: Ego Draconis [IT'"]}>,
...

or

Traceback (most recent call last):

 File "/usr/lib/python2.5/site-packages/django/core/handlers/base.py", line 100, in get_response
   response = callback(request, _callback_args, *_callback_kwargs)

 File "/usr/lib/python2.5/site-packages/mongo_autocomplete/views.py", line 13, in autocomplete
   items = Item.objects(label__istartswith=query)[:MAX_RESULTS]

 File "build/bdist.linux-i686/egg/mongoengine/queryset.py", line 215, in **call**
   query = QuerySet._transform_query(_doc_cls=self._document, **query)

 File "build/bdist.linux-i686/egg/mongoengine/queryset.py", line 322, in _transform_query
   value = field.prepare_query_value(op, value)

 File "build/bdist.linux-i686/egg/mongoengine/fields.py", line 60, in prepare_query_value
   value = re.compile(regex % value, flags)

 File "/usr/lib/python2.5/re.py", line 188, in compile
   return _compile(pattern, flags)

 File "/usr/lib/python2.5/re.py", line 241, in _compile
   raise error, v # invalid expression

error: unbalanced parenthesis

<WSGIRequest
GET:<QueryDict: {u'term': [u'cantina cast. peach (pass']}>,
...

The error is almost transparent for the users, as the request is made in ajax, so they simply  get a 500 response and no results displayed, but you can easily imagine other situations where this error can be much more visible.
As you can receive basically every possible string (including reserved chars), escaping the value should fix the problem.
At line 67 of fields.py
value = re.compile(regex % value, flags)
becomes
value = re.compile(re.escape(regex % value), flags)
I hope this help!

Germano

**Comment by flosch** [comment]
Thanks Germano, I'll take a look on this.

**Comment by flosch** [comment]
Fixed in http://github.com/flosch/mongoengine/commit/7ab2e21c106fc89875b1ae4ae79ecd7e0988ded3

Will be in v0.4 branch soon. Thanks!

**Comment by GermanoGuerrini** [comment]
Great, keep up the good work!
